### ISSUE TITLE
Django 1.7 support

### ISSUE THREAD

**Issue by acdha** [django-haystack/django-haystack#1067]
- [x] #982 Handle `module_name` to `model_name` rename
- [x] #1016 Handle the new app registry system
- [ ] #1069 Update test mocks to deal with Django 1.7's registry
